# Generated by Django 3.0.8 on 2020-07-25 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentMarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
